@startmindmap

* Idea Box

** Widget (Connection Token)
*** Envoie Requête de question
*** Récupération question


left side

** Site
*** Connexion/Inscription

*** Admin
**** Supprimer client
**** Voir les stats de IdeaBox


*** Client
**** README implémentation

**** CRUD Application (Création Token)

**** CRUD Campagne
***** CRUD questions
****** Défenir récurences
****** Définir champs

**** Associer une campagne à une app


**** Récupérer données pour une app
**** Récupérer données pour une campagne

@endmindmap